locale                   : "en-US"
title                    : "doesnotexists"
title_separator          : "-"
subtitle                 : testing
name                     : "y0on"
description              : "API Testing Website"
url                      : "http://doesnotexists.github.io"
baseurl                  : ""